"""caption and dual subtitle preferences

Revision ID: 59d824385095
Revises: a5bff093bc24
Create Date: 2026-08-15 23:04:44.961091
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "59d824385095"
down_revision: str | Sequence[str] | None = "a5bff093bc24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile_preferences",
        sa.Column("preferred_secondary_subtitle_language", sa.String(length=16), nullable=True),
    )
    op.add_column(
        "profile_preferences",
        sa.Column("caption_size", sa.String(length=16), server_default="medium", nullable=False),
    )
    op.add_column(
        "profile_preferences",
        sa.Column(
            "caption_background", sa.String(length=16), server_default="shadow", nullable=False
        ),
    )
    op.add_column(
        "profile_preferences",
        sa.Column(
            "caption_position", sa.String(length=16), server_default="bottom", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile_preferences", "caption_position")
    op.drop_column("profile_preferences", "caption_background")
    op.drop_column("profile_preferences", "caption_size")
    op.drop_column("profile_preferences", "preferred_secondary_subtitle_language")
    # ### end Alembic commands ###
