"""catalog domain

Revision ID: 638bc495ce1d
Revises: 20260815_0003
Create Date: 2026-08-15 17:11:18.503991
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "638bc495ce1d"
down_revision: str | Sequence[str] | None = "20260815_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)
    op.create_index(op.f("ix_characters_slug"), "characters", ["slug"], unique=True)
    op.create_table(
        "countries",
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "franchises",
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_franchises_slug"), "franchises", ["slug"], unique=True)
    op.create_table(
        "genres",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_genres_slug"), "genres", ["slug"], unique=True)
    op.create_table(
        "languages",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_slug"), "tags", ["slug"], unique=True)
    op.create_table(
        "themes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_themes_slug"), "themes", ["slug"], unique=True)
    op.create_table(
        "companies",
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_slug"), "companies", ["slug"], unique=True)
    op.create_table(
        "movies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("slug", sa.String(length=280), nullable=False),
        sa.Column("original_title", sa.String(length=250), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("runtime_minutes", sa.Integer(), nullable=False),
        sa.Column("maturity_rating", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "ready", "published", "archived", name="catalog_status"),
            nullable=False,
        ),
        sa.Column("original_language_code", sa.String(length=16), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("franchise_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("runtime_minutes > 0", name="ck_movies_runtime_positive"),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.ForeignKeyConstraint(
            ["franchise_id"],
            ["franchises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["original_language_code"],
            ["languages.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movies_release_date"), "movies", ["release_date"], unique=False)
    op.create_index(op.f("ix_movies_slug"), "movies", ["slug"], unique=True)
    op.create_index(op.f("ix_movies_status"), "movies", ["status"], unique=False)
    op.create_index(
        "ix_movies_status_release_date", "movies", ["status", "release_date"], unique=False
    )
    op.create_index(op.f("ix_movies_title"), "movies", ["title"], unique=False)
    op.create_table(
        "people",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("biography", sa.Text(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_people_name"), "people", ["name"], unique=False)
    op.create_index(op.f("ix_people_slug"), "people", ["slug"], unique=True)
    op.create_table(
        "series",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("slug", sa.String(length=280), nullable=False),
        sa.Column("original_title", sa.String(length=250), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("maturity_rating", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "ready", "published", "archived", name="catalog_status"),
            nullable=False,
        ),
        sa.Column("original_language_code", sa.String(length=16), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("franchise_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.ForeignKeyConstraint(
            ["franchise_id"],
            ["franchises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["original_language_code"],
            ["languages.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_series_release_date"), "series", ["release_date"], unique=False)
    op.create_index(op.f("ix_series_slug"), "series", ["slug"], unique=True)
    op.create_index(op.f("ix_series_status"), "series", ["status"], unique=False)
    op.create_index(
        "ix_series_status_release_date", "series", ["status", "release_date"], unique=False
    )
    op.create_index(op.f("ix_series_title"), "series", ["title"], unique=False)
    op.create_table(
        "movie_genres",
        sa.Column("movie_id", sa.UUID(), nullable=False),
        sa.Column("genre_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("movie_id", "genre_id"),
    )
    op.create_table(
        "movie_tags",
        sa.Column("movie_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("movie_id", "tag_id"),
    )
    op.create_table(
        "movie_themes",
        sa.Column("movie_id", sa.UUID(), nullable=False),
        sa.Column("theme_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["theme_id"], ["themes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("movie_id", "theme_id"),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("series_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=True),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "number", name="uq_seasons_series_number"),
    )
    op.create_index(op.f("ix_seasons_series_id"), "seasons", ["series_id"], unique=False)
    op.create_table(
        "series_genres",
        sa.Column("series_id", sa.UUID(), nullable=False),
        sa.Column("genre_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("series_id", "genre_id"),
    )
    op.create_table(
        "episodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=False),
        sa.Column("runtime_minutes", sa.Integer(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "ready", "published", "archived", name="catalog_status"),
            nullable=False,
        ),
        sa.CheckConstraint("runtime_minutes > 0", name="ck_episodes_runtime_positive"),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "number", name="uq_episodes_season_number"),
    )
    op.create_index(op.f("ix_episodes_season_id"), "episodes", ["season_id"], unique=False)
    op.create_index(op.f("ix_episodes_title"), "episodes", ["title"], unique=False)
    op.create_table(
        "artwork",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=True),
        sa.Column("series_id", sa.UUID(), nullable=True),
        sa.Column("season_id", sa.UUID(), nullable=True),
        sa.Column("episode_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "poster", "landscape", "backdrop", "logo", "mobile", "still", name="artwork_kind"
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("alt_text", sa.String(length=500), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(movie_id IS NOT NULL)::integer + (series_id IS NOT NULL)::integer + "
            "(season_id IS NOT NULL)::integer + (episode_id IS NOT NULL)::integer = 1",
            name="ck_artwork_one_title",
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artwork_episode_id"), "artwork", ["episode_id"], unique=False)
    op.create_index(op.f("ix_artwork_movie_id"), "artwork", ["movie_id"], unique=False)
    op.create_index("ix_artwork_movie_kind", "artwork", ["movie_id", "kind"], unique=False)
    op.create_index(op.f("ix_artwork_season_id"), "artwork", ["season_id"], unique=False)
    op.create_index(op.f("ix_artwork_series_id"), "artwork", ["series_id"], unique=False)
    op.create_table(
        "credits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=True),
        sa.Column("series_id", sa.UUID(), nullable=True),
        sa.Column("episode_id", sa.UUID(), nullable=True),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("billing_order", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(movie_id IS NOT NULL)::integer + (series_id IS NOT NULL)::integer + "
            "(episode_id IS NOT NULL)::integer = 1",
            name="ck_credits_one_title",
        ),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credits_episode_id"), "credits", ["episode_id"], unique=False)
    op.create_index(op.f("ix_credits_movie_id"), "credits", ["movie_id"], unique=False)
    op.create_index(op.f("ix_credits_person_id"), "credits", ["person_id"], unique=False)
    op.create_index("ix_credits_person_role", "credits", ["person_id", "role"], unique=False)
    op.create_index(op.f("ix_credits_series_id"), "credits", ["series_id"], unique=False)
    op.create_table(
        "editions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=True),
        sa.Column("episode_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "(movie_id IS NOT NULL)::integer + (episode_id IS NOT NULL)::integer = 1",
            name="ck_editions_one_parent",
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("episode_id", "name", name="uq_editions_episode_name"),
        sa.UniqueConstraint("movie_id", "name", name="uq_editions_movie_name"),
    )
    op.create_index(op.f("ix_editions_episode_id"), "editions", ["episode_id"], unique=False)
    op.create_index(op.f("ix_editions_movie_id"), "editions", ["movie_id"], unique=False)
    op.create_table(
        "trailer_clips",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=True),
        sa.Column("series_id", sa.UUID(), nullable=True),
        sa.Column("episode_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.Enum("trailer", "clip", name="preview_kind"), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("external_url", sa.String(length=1000), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(movie_id IS NOT NULL)::integer + (series_id IS NOT NULL)::integer + "
            "(episode_id IS NOT NULL)::integer = 1",
            name="ck_trailer_clips_one_title",
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trailer_clips_episode_id"), "trailer_clips", ["episode_id"], unique=False
    )
    op.create_index(op.f("ix_trailer_clips_movie_id"), "trailer_clips", ["movie_id"], unique=False)
    op.create_index(
        op.f("ix_trailer_clips_series_id"), "trailer_clips", ["series_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trailer_clips_series_id"), table_name="trailer_clips")
    op.drop_index(op.f("ix_trailer_clips_movie_id"), table_name="trailer_clips")
    op.drop_index(op.f("ix_trailer_clips_episode_id"), table_name="trailer_clips")
    op.drop_table("trailer_clips")
    op.drop_index(op.f("ix_editions_movie_id"), table_name="editions")
    op.drop_index(op.f("ix_editions_episode_id"), table_name="editions")
    op.drop_table("editions")
    op.drop_index(op.f("ix_credits_series_id"), table_name="credits")
    op.drop_index("ix_credits_person_role", table_name="credits")
    op.drop_index(op.f("ix_credits_person_id"), table_name="credits")
    op.drop_index(op.f("ix_credits_movie_id"), table_name="credits")
    op.drop_index(op.f("ix_credits_episode_id"), table_name="credits")
    op.drop_table("credits")
    op.drop_index(op.f("ix_artwork_series_id"), table_name="artwork")
    op.drop_index(op.f("ix_artwork_season_id"), table_name="artwork")
    op.drop_index("ix_artwork_movie_kind", table_name="artwork")
    op.drop_index(op.f("ix_artwork_movie_id"), table_name="artwork")
    op.drop_index(op.f("ix_artwork_episode_id"), table_name="artwork")
    op.drop_table("artwork")
    op.drop_index(op.f("ix_episodes_title"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_season_id"), table_name="episodes")
    op.drop_table("episodes")
    op.drop_table("series_genres")
    op.drop_index(op.f("ix_seasons_series_id"), table_name="seasons")
    op.drop_table("seasons")
    op.drop_table("movie_themes")
    op.drop_table("movie_tags")
    op.drop_table("movie_genres")
    op.drop_index(op.f("ix_series_title"), table_name="series")
    op.drop_index("ix_series_status_release_date", table_name="series")
    op.drop_index(op.f("ix_series_status"), table_name="series")
    op.drop_index(op.f("ix_series_slug"), table_name="series")
    op.drop_index(op.f("ix_series_release_date"), table_name="series")
    op.drop_table("series")
    op.drop_index(op.f("ix_people_slug"), table_name="people")
    op.drop_index(op.f("ix_people_name"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_movies_title"), table_name="movies")
    op.drop_index("ix_movies_status_release_date", table_name="movies")
    op.drop_index(op.f("ix_movies_status"), table_name="movies")
    op.drop_index(op.f("ix_movies_slug"), table_name="movies")
    op.drop_index(op.f("ix_movies_release_date"), table_name="movies")
    op.drop_table("movies")
    op.drop_index(op.f("ix_companies_slug"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_themes_slug"), table_name="themes")
    op.drop_table("themes")
    op.drop_index(op.f("ix_tags_slug"), table_name="tags")
    op.drop_table("tags")
    op.drop_table("languages")
    op.drop_index(op.f("ix_genres_slug"), table_name="genres")
    op.drop_table("genres")
    op.drop_index(op.f("ix_franchises_slug"), table_name="franchises")
    op.drop_table("franchises")
    op.drop_table("countries")
    op.drop_index(op.f("ix_characters_slug"), table_name="characters")
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_table("characters")
    op.execute("DROP TYPE IF EXISTS preview_kind")
    op.execute("DROP TYPE IF EXISTS artwork_kind")
    op.execute("DROP TYPE IF EXISTS catalog_status")
    # ### end Alembic commands ###
