"""moderated community foundation

Revision ID: 6b0b76795b1e
Revises: 20260815_0021
Create Date: 2026-08-15 22:15:18.485467
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6b0b76795b1e"
down_revision: str | Sequence[str] | None = "20260815_0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_follows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("follower_profile_id", sa.UUID(), nullable=False),
        sa.Column("followed_profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "follower_profile_id <> followed_profile_id", name="ck_profile_follows_not_self"
        ),
        sa.ForeignKeyConstraint(["followed_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["follower_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "follower_profile_id", "followed_profile_id", name="uq_profile_follows"
        ),
    )
    op.create_index(
        op.f("ix_profile_follows_followed_profile_id"),
        "profile_follows",
        ["followed_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_follows_follower_profile_id"),
        "profile_follows",
        ["follower_profile_id"],
        unique=False,
    )
    op.create_table(
        "profile_safety_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_profile_id", sa.UUID(), nullable=False),
        sa.Column("target_profile_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("block", "mute", name="safety_relation_kind"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_profile_id <> target_profile_id", name="ck_profile_safety_not_self"
        ),
        sa.ForeignKeyConstraint(["actor_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "actor_profile_id", "target_profile_id", "kind", name="uq_profile_safety"
        ),
    )
    op.create_index(
        op.f("ix_profile_safety_relations_actor_profile_id"),
        "profile_safety_relations",
        ["actor_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_safety_relations_target_profile_id"),
        "profile_safety_relations",
        ["target_profile_id"],
        unique=False,
    )
    op.create_table(
        "ratings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("score >= 1 AND score <= 5", name="ck_ratings_score"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "movie_id", name="uq_ratings_profile_movie"),
    )
    op.create_index(op.f("ix_ratings_movie_id"), "ratings", ["movie_id"], unique=False)
    op.create_index(op.f("ix_ratings_profile_id"), "ratings", ["profile_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=False),
        sa.Column("headline", sa.String(length=140), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("contains_spoilers", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", "removed", name="moderation_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("moderation_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("char_length(body) BETWEEN 1 AND 5000", name="ck_reviews_body_length"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "movie_id", name="uq_reviews_profile_movie"),
    )
    op.create_index(op.f("ix_reviews_movie_id"), "reviews", ["movie_id"], unique=False)
    op.create_index(op.f("ix_reviews_profile_id"), "reviews", ["profile_id"], unique=False)
    op.create_index(op.f("ix_reviews_status"), "reviews", ["status"], unique=False)
    op.create_table(
        "community_activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "review_published",
                "list_published",
                "profile_followed",
                name="community_activity_kind",
            ),
            nullable=False,
        ),
        sa.Column("review_id", sa.UUID(), nullable=True),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column("target_profile_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'review_published' AND review_id IS NOT NULL AND "
            "collection_id IS NULL AND target_profile_id IS NULL) OR "
            "(kind = 'list_published' AND review_id IS NULL AND "
            "collection_id IS NOT NULL AND target_profile_id IS NULL) OR "
            "(kind = 'profile_followed' AND review_id IS NULL AND "
            "collection_id IS NULL AND target_profile_id IS NOT NULL)",
            name="ck_community_activities_target_kind",
        ),
        sa.ForeignKeyConstraint(["actor_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_community_activities_actor_profile_id"),
        "community_activities",
        ["actor_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_activities_collection_id"),
        "community_activities",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_activities_kind"), "community_activities", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_community_activities_review_id"),
        "community_activities",
        ["review_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_activities_target_profile_id"),
        "community_activities",
        ["target_profile_id"],
        unique=False,
    )
    op.create_table(
        "community_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reporter_profile_id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=True),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "harassment",
                "hate",
                "spam",
                "spoiler",
                "impersonation",
                "other",
                name="report_reason",
            ),
            nullable=False,
        ),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "reviewing", "resolved", "dismissed", name="report_status"),
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(review_id IS NOT NULL)::integer + (collection_id IS NOT NULL)::integer = 1",
            name="ck_community_reports_one_target",
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reporter_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reporter_profile_id", "collection_id", name="uq_reports_profile_collection"
        ),
        sa.UniqueConstraint("reporter_profile_id", "review_id", name="uq_reports_profile_review"),
    )
    op.create_index(
        op.f("ix_community_reports_collection_id"),
        "community_reports",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_reports_reporter_profile_id"),
        "community_reports",
        ["reporter_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_reports_review_id"), "community_reports", ["review_id"], unique=False
    )
    op.create_index(
        op.f("ix_community_reports_status"), "community_reports", ["status"], unique=False
    )
    op.create_table(
        "moderation_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("admin_id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=True),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column("report_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(review_id IS NOT NULL)::integer + "
            "(collection_id IS NOT NULL)::integer + "
            "(report_id IS NOT NULL)::integer <= 1",
            name="ck_moderation_actions_at_most_one_target",
        ),
        sa.ForeignKeyConstraint(["admin_id"], ["admins.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["report_id"], ["community_reports.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_moderation_actions_admin_id"), "moderation_actions", ["admin_id"], unique=False
    )
    op.create_index(
        op.f("ix_moderation_actions_collection_id"),
        "moderation_actions",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_moderation_actions_report_id"), "moderation_actions", ["report_id"], unique=False
    )
    op.create_index(
        op.f("ix_moderation_actions_review_id"), "moderation_actions", ["review_id"], unique=False
    )
    op.add_column(
        "collections",
        sa.Column("visibility", sa.String(length=16), server_default="private", nullable=False),
    )
    op.add_column(
        "collections",
        sa.Column(
            "moderation_status", sa.String(length=16), server_default="pending", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_collections_moderation_status"), "collections", ["moderation_status"], unique=False
    )
    op.create_check_constraint(
        "ck_collections_visibility",
        "collections",
        "visibility IN ('private', 'unlisted', 'public')",
    )
    op.create_check_constraint(
        "ck_collections_moderation_status",
        "collections",
        "moderation_status IN ('pending', 'approved', 'rejected', 'removed')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE collections DROP CONSTRAINT IF EXISTS ck_collections_moderation_status")
    op.execute("ALTER TABLE collections DROP CONSTRAINT IF EXISTS ck_collections_visibility")
    op.drop_index(op.f("ix_collections_moderation_status"), table_name="collections")
    op.drop_column("collections", "moderation_status")
    op.drop_column("collections", "visibility")
    op.drop_index(op.f("ix_moderation_actions_review_id"), table_name="moderation_actions")
    op.drop_index(op.f("ix_moderation_actions_report_id"), table_name="moderation_actions")
    op.drop_index(op.f("ix_moderation_actions_collection_id"), table_name="moderation_actions")
    op.drop_index(op.f("ix_moderation_actions_admin_id"), table_name="moderation_actions")
    op.drop_table("moderation_actions")
    op.drop_index(op.f("ix_community_reports_status"), table_name="community_reports")
    op.drop_index(op.f("ix_community_reports_review_id"), table_name="community_reports")
    op.drop_index(op.f("ix_community_reports_reporter_profile_id"), table_name="community_reports")
    op.drop_index(op.f("ix_community_reports_collection_id"), table_name="community_reports")
    op.drop_table("community_reports")
    op.drop_index(
        op.f("ix_community_activities_target_profile_id"), table_name="community_activities"
    )
    op.drop_index(op.f("ix_community_activities_review_id"), table_name="community_activities")
    op.drop_index(op.f("ix_community_activities_kind"), table_name="community_activities")
    op.drop_index(op.f("ix_community_activities_collection_id"), table_name="community_activities")
    op.drop_index(
        op.f("ix_community_activities_actor_profile_id"), table_name="community_activities"
    )
    op.drop_table("community_activities")
    op.drop_index(op.f("ix_reviews_status"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_profile_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_movie_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_ratings_profile_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_movie_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(
        op.f("ix_profile_safety_relations_target_profile_id"), table_name="profile_safety_relations"
    )
    op.drop_index(
        op.f("ix_profile_safety_relations_actor_profile_id"), table_name="profile_safety_relations"
    )
    op.drop_table("profile_safety_relations")
    op.drop_index(op.f("ix_profile_follows_follower_profile_id"), table_name="profile_follows")
    op.drop_index(op.f("ix_profile_follows_followed_profile_id"), table_name="profile_follows")
    op.drop_table("profile_follows")
    sa.Enum(name="community_activity_kind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="report_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="report_reason").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="moderation_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="safety_relation_kind").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
