"""profile timezone preference

Revision ID: a5bff093bc24
Revises: af1c7a7c659d
Create Date: 2026-08-15 22:54:39.894635
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a5bff093bc24"
down_revision: str | Sequence[str] | None = "af1c7a7c659d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile_preferences",
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile_preferences", "timezone")
    # ### end Alembic commands ###
