"""movie clubs and watch parties

Revision ID: af1c7a7c659d
Revises: 6b0b76795b1e
Create Date: 2026-08-15 22:38:09.474333
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "af1c7a7c659d"
down_revision: str | Sequence[str] | None = "6b0b76795b1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_clubs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_profile_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("invite_token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invite_token_hash"),
    )
    op.create_index(
        op.f("ix_movie_clubs_owner_profile_id"), "movie_clubs", ["owner_profile_id"], unique=False
    )
    op.create_index(op.f("ix_movie_clubs_slug"), "movie_clubs", ["slug"], unique=True)
    op.create_table(
        "club_collections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("added_by_profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["added_by_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["club_id"], ["movie_clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("club_id", "collection_id", name="uq_club_collections"),
    )
    op.create_index(
        op.f("ix_club_collections_club_id"), "club_collections", ["club_id"], unique=False
    )
    op.create_table(
        "club_discussion_posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("contains_spoilers", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(body) BETWEEN 1 AND 3000", name="ck_club_posts_body"),
        sa.ForeignKeyConstraint(["club_id"], ["movie_clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_club_discussion_posts_club_id"), "club_discussion_posts", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_club_discussion_posts_created_at"),
        "club_discussion_posts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_club_discussion_posts_profile_id"),
        "club_discussion_posts",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "club_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "role", sa.Enum("owner", "moderator", "member", name="club_role"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("invited", "active", "left", "removed", name="club_membership_status"),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["club_id"], ["movie_clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("club_id", "profile_id", name="uq_club_memberships_profile"),
    )
    op.create_index(
        op.f("ix_club_memberships_club_id"), "club_memberships", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_club_memberships_profile_id"), "club_memberships", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_club_memberships_status"), "club_memberships", ["status"], unique=False
    )
    op.create_table(
        "club_polls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("created_by_profile_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.String(length=300), nullable=False),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["club_id"], ["movie_clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_club_polls_club_id"), "club_polls", ["club_id"], unique=False)
    op.create_table(
        "club_poll_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("poll_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["poll_id"], ["club_polls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("poll_id", "position", name="uq_club_poll_options_position"),
    )
    op.create_index(
        op.f("ix_club_poll_options_poll_id"), "club_poll_options", ["poll_id"], unique=False
    )
    op.create_table(
        "club_poll_votes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("poll_id", sa.UUID(), nullable=False),
        sa.Column("option_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["option_id"], ["club_poll_options.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["poll_id"], ["club_polls.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("poll_id", "profile_id", name="uq_club_poll_votes_profile"),
    )
    op.create_index(
        op.f("ix_club_poll_votes_poll_id"), "club_poll_votes", ["poll_id"], unique=False
    )
    op.create_index(
        op.f("ix_club_poll_votes_profile_id"), "club_poll_votes", ["profile_id"], unique=False
    )
    op.create_table(
        "club_scheduled_watches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=False),
        sa.Column("playback_source_id", sa.UUID(), nullable=True),
        sa.Column("created_by_profile_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("scheduled", "active", "completed", "cancelled", name="club_watch_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["club_id"], ["movie_clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["playback_source_id"], ["playback_sources.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_club_scheduled_watches_club_id"),
        "club_scheduled_watches",
        ["club_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_club_scheduled_watches_movie_id"),
        "club_scheduled_watches",
        ["movie_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_club_scheduled_watches_scheduled_at"),
        "club_scheduled_watches",
        ["scheduled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_club_scheduled_watches_status"), "club_scheduled_watches", ["status"], unique=False
    )
    op.create_table(
        "club_watch_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scheduled_watch_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("completed", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["scheduled_watch_id"], ["club_scheduled_watches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scheduled_watch_id", "profile_id", name="uq_club_watch_history_profile"
        ),
    )
    op.create_index(
        op.f("ix_club_watch_history_profile_id"), "club_watch_history", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_club_watch_history_scheduled_watch_id"),
        "club_watch_history",
        ["scheduled_watch_id"],
        unique=False,
    )
    op.create_table(
        "watch_parties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scheduled_watch_id", sa.UUID(), nullable=False),
        sa.Column("playback_source_id", sa.UUID(), nullable=False),
        sa.Column("host_profile_id", sa.UUID(), nullable=False),
        sa.Column("access_token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum("waiting", "playing", "paused", "ended", name="party_state"),
            nullable=False,
        ),
        sa.Column("position_seconds", sa.Float(), server_default="0", nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "state_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position_seconds >= 0", name="ck_watch_parties_position"),
        sa.ForeignKeyConstraint(["host_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["playback_source_id"], ["playback_sources.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_watch_id"], ["club_scheduled_watches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token_hash"),
        sa.UniqueConstraint("scheduled_watch_id"),
    )
    op.create_index(
        op.f("ix_watch_parties_host_profile_id"), "watch_parties", ["host_profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_watch_parties_playback_source_id"),
        "watch_parties",
        ["playback_source_id"],
        unique=False,
    )
    op.create_table(
        "watch_party_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("actor_profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("play", "pause", "seek", "ended", name="party_event_kind"),
            nullable=False,
        ),
        sa.Column("position_seconds", sa.Float(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position_seconds >= 0", name="ck_watch_party_events_position"),
        sa.ForeignKeyConstraint(["actor_profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["party_id"], ["watch_parties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("party_id", "revision", name="uq_watch_party_events_revision"),
    )
    op.create_index(
        op.f("ix_watch_party_events_party_id"), "watch_party_events", ["party_id"], unique=False
    )
    op.create_table(
        "watch_party_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind", sa.Enum("message", "reaction", name="party_message_kind"), nullable=False
        ),
        sa.Column("body", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(body) BETWEEN 1 AND 500", name="ck_watch_party_messages_body"
        ),
        sa.ForeignKeyConstraint(["party_id"], ["watch_parties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_watch_party_messages_created_at"),
        "watch_party_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_party_messages_party_id"), "watch_party_messages", ["party_id"], unique=False
    )
    op.create_index(
        op.f("ix_watch_party_messages_profile_id"),
        "watch_party_messages",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "watch_party_participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("entitlement_verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["party_id"], ["watch_parties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("party_id", "profile_id", name="uq_watch_party_participants_profile"),
    )
    op.create_index(
        op.f("ix_watch_party_participants_party_id"),
        "watch_party_participants",
        ["party_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_party_participants_profile_id"),
        "watch_party_participants",
        ["profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_watch_party_participants_profile_id"), table_name="watch_party_participants"
    )
    op.drop_index(
        op.f("ix_watch_party_participants_party_id"), table_name="watch_party_participants"
    )
    op.drop_table("watch_party_participants")
    op.drop_index(op.f("ix_watch_party_messages_profile_id"), table_name="watch_party_messages")
    op.drop_index(op.f("ix_watch_party_messages_party_id"), table_name="watch_party_messages")
    op.drop_index(op.f("ix_watch_party_messages_created_at"), table_name="watch_party_messages")
    op.drop_table("watch_party_messages")
    op.drop_index(op.f("ix_watch_party_events_party_id"), table_name="watch_party_events")
    op.drop_table("watch_party_events")
    op.drop_index(op.f("ix_watch_parties_playback_source_id"), table_name="watch_parties")
    op.drop_index(op.f("ix_watch_parties_host_profile_id"), table_name="watch_parties")
    op.drop_table("watch_parties")
    op.drop_index(op.f("ix_club_watch_history_scheduled_watch_id"), table_name="club_watch_history")
    op.drop_index(op.f("ix_club_watch_history_profile_id"), table_name="club_watch_history")
    op.drop_table("club_watch_history")
    op.drop_index(op.f("ix_club_scheduled_watches_status"), table_name="club_scheduled_watches")
    op.drop_index(
        op.f("ix_club_scheduled_watches_scheduled_at"), table_name="club_scheduled_watches"
    )
    op.drop_index(op.f("ix_club_scheduled_watches_movie_id"), table_name="club_scheduled_watches")
    op.drop_index(op.f("ix_club_scheduled_watches_club_id"), table_name="club_scheduled_watches")
    op.drop_table("club_scheduled_watches")
    op.drop_index(op.f("ix_club_poll_votes_profile_id"), table_name="club_poll_votes")
    op.drop_index(op.f("ix_club_poll_votes_poll_id"), table_name="club_poll_votes")
    op.drop_table("club_poll_votes")
    op.drop_index(op.f("ix_club_poll_options_poll_id"), table_name="club_poll_options")
    op.drop_table("club_poll_options")
    op.drop_index(op.f("ix_club_polls_club_id"), table_name="club_polls")
    op.drop_table("club_polls")
    op.drop_index(op.f("ix_club_memberships_status"), table_name="club_memberships")
    op.drop_index(op.f("ix_club_memberships_profile_id"), table_name="club_memberships")
    op.drop_index(op.f("ix_club_memberships_club_id"), table_name="club_memberships")
    op.drop_table("club_memberships")
    op.drop_index(op.f("ix_club_discussion_posts_profile_id"), table_name="club_discussion_posts")
    op.drop_index(op.f("ix_club_discussion_posts_created_at"), table_name="club_discussion_posts")
    op.drop_index(op.f("ix_club_discussion_posts_club_id"), table_name="club_discussion_posts")
    op.drop_table("club_discussion_posts")
    op.drop_index(op.f("ix_club_collections_club_id"), table_name="club_collections")
    op.drop_table("club_collections")
    op.drop_index(op.f("ix_movie_clubs_slug"), table_name="movie_clubs")
    op.drop_index(op.f("ix_movie_clubs_owner_profile_id"), table_name="movie_clubs")
    op.drop_table("movie_clubs")
    sa.Enum(name="party_message_kind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="party_event_kind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="party_state").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="club_watch_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="club_membership_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="club_role").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
