"""edition vault and verified comparisons

Revision ID: 20260815_0017
Revises: 20260815_0016
Create Date: 2026-08-15 21:13:26.676208
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260815_0017"
down_revision: str | Sequence[str] | None = "20260815_0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edition_differences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_edition_id", sa.UUID(), nullable=False),
        sa.Column("target_edition_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "inserted_scene",
                "removed_scene",
                "presentation",
                "restoration",
                "audio",
                "editorial",
                name="edition_difference_kind",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reveal_seconds", sa.Float(), nullable=True),
        sa.Column("source_note", sa.Text(), nullable=False),
        sa.Column("manually_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "reveal_seconds IS NULL OR reveal_seconds >= 0", name="ck_edition_differences_reveal"
        ),
        sa.CheckConstraint(
            "source_edition_id <> target_edition_id", name="ck_edition_differences_distinct"
        ),
        sa.ForeignKeyConstraint(["source_edition_id"], ["editions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_edition_id"], ["editions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_edition_id",
            "target_edition_id",
            "kind",
            "description",
            name="uq_edition_differences_fact",
        ),
    )
    op.create_index(
        op.f("ix_edition_differences_source_edition_id"),
        "edition_differences",
        ["source_edition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_edition_differences_target_edition_id"),
        "edition_differences",
        ["target_edition_id"],
        unique=False,
    )
    op.add_column(
        "editions", sa.Column("rights_start_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("editions", sa.Column("rights_end_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "editions",
        sa.Column("intended_presentation", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("editions", sa.Column("aspect_ratio", sa.String(length=32), nullable=True))
    op.add_column("editions", sa.Column("frame_rate", sa.Float(), nullable=True))
    op.add_column(
        "editions", sa.Column("presentation_format", sa.String(length=120), nullable=True)
    )
    op.add_column("editions", sa.Column("capture_format", sa.String(length=120), nullable=True))
    op.add_column("editions", sa.Column("audio_format", sa.String(length=120), nullable=True))
    op.add_column(
        "editions", sa.Column("original_language_code", sa.String(length=16), nullable=True)
    )
    op.add_column("editions", sa.Column("restoration_info", sa.Text(), nullable=True))
    op.add_column("editions", sa.Column("source_info", sa.Text(), nullable=True))
    op.create_index(op.f("ix_editions_rights_end_at"), "editions", ["rights_end_at"], unique=False)
    op.create_index(
        op.f("ix_editions_rights_start_at"), "editions", ["rights_start_at"], unique=False
    )
    op.create_foreign_key(
        "fk_editions_original_language_code_languages",
        "editions",
        "languages",
        ["original_language_code"],
        ["code"],
    )
    op.create_check_constraint(
        "ck_editions_frame_rate", "editions", "frame_rate IS NULL OR frame_rate > 0"
    )
    op.create_check_constraint(
        "ck_editions_rights_window",
        "editions",
        "rights_start_at IS NULL OR rights_end_at IS NULL OR rights_end_at > rights_start_at",
    )
    op.add_column("playback_sources", sa.Column("edition_id", sa.UUID(), nullable=True))
    op.drop_constraint(op.f("uq_playback_sources_episode"), "playback_sources", type_="unique")
    op.drop_constraint(op.f("uq_playback_sources_movie"), "playback_sources", type_="unique")
    op.create_index(
        op.f("ix_playback_sources_edition_id"), "playback_sources", ["edition_id"], unique=True
    )
    op.create_index(
        "uq_playback_sources_legacy_episode",
        "playback_sources",
        ["episode_id"],
        unique=True,
        postgresql_where=sa.text("edition_id IS NULL AND episode_id IS NOT NULL"),
    )
    op.create_index(
        "uq_playback_sources_legacy_movie",
        "playback_sources",
        ["movie_id"],
        unique=True,
        postgresql_where=sa.text("edition_id IS NULL AND movie_id IS NOT NULL"),
    )
    op.create_foreign_key(
        "fk_playback_sources_edition_id_editions",
        "playback_sources",
        "editions",
        ["edition_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM playback_sources WHERE edition_id IS NOT NULL")
    op.drop_constraint(
        "fk_playback_sources_edition_id_editions", "playback_sources", type_="foreignkey"
    )
    op.drop_index(
        "uq_playback_sources_legacy_movie",
        table_name="playback_sources",
        postgresql_where=sa.text("edition_id IS NULL AND movie_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_playback_sources_legacy_episode",
        table_name="playback_sources",
        postgresql_where=sa.text("edition_id IS NULL AND episode_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_playback_sources_edition_id"), table_name="playback_sources")
    op.create_unique_constraint(
        op.f("uq_playback_sources_movie"),
        "playback_sources",
        ["movie_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_playback_sources_episode"),
        "playback_sources",
        ["episode_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("playback_sources", "edition_id")
    op.drop_constraint("ck_editions_rights_window", "editions", type_="check")
    op.drop_constraint("ck_editions_frame_rate", "editions", type_="check")
    op.drop_constraint(
        "fk_editions_original_language_code_languages", "editions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_editions_rights_start_at"), table_name="editions")
    op.drop_index(op.f("ix_editions_rights_end_at"), table_name="editions")
    op.drop_column("editions", "source_info")
    op.drop_column("editions", "restoration_info")
    op.drop_column("editions", "original_language_code")
    op.drop_column("editions", "audio_format")
    op.drop_column("editions", "capture_format")
    op.drop_column("editions", "presentation_format")
    op.drop_column("editions", "frame_rate")
    op.drop_column("editions", "aspect_ratio")
    op.drop_column("editions", "intended_presentation")
    op.drop_column("editions", "rights_end_at")
    op.drop_column("editions", "rights_start_at")
    op.drop_index(
        op.f("ix_edition_differences_target_edition_id"), table_name="edition_differences"
    )
    op.drop_index(
        op.f("ix_edition_differences_source_edition_id"), table_name="edition_differences"
    )
    op.drop_table("edition_differences")
    sa.Enum(name="edition_difference_kind").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
