"""scene bookmarks and notes

Revision ID: 20260815_0014
Revises: 20260815_0013
Create Date: 2026-08-15 20:17:01.630057
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260815_0014"
down_revision: str | Sequence[str] | None = "20260815_0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scene_bookmarks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("playback_source_id", sa.UUID(), nullable=False),
        sa.Column("scene_id", sa.UUID(), nullable=True),
        sa.Column("timestamp_seconds", sa.Float(), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("timestamp_seconds >= 0", name="ck_scene_bookmarks_timestamp"),
        sa.ForeignKeyConstraint(
            ["playback_source_id"], ["playback_sources.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scene_bookmarks_playback_source_id"),
        "scene_bookmarks",
        ["playback_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scene_bookmarks_profile_id"), "scene_bookmarks", ["profile_id"], unique=False
    )
    op.create_index(
        "ix_scene_bookmarks_profile_source",
        "scene_bookmarks",
        ["profile_id", "playback_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scene_bookmarks_scene_id"), "scene_bookmarks", ["scene_id"], unique=False
    )
    op.create_table(
        "scene_notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("playback_source_id", sa.UUID(), nullable=False),
        sa.Column("scene_id", sa.UUID(), nullable=True),
        sa.Column("timestamp_seconds", sa.Float(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("timestamp_seconds >= 0", name="ck_scene_notes_timestamp"),
        sa.ForeignKeyConstraint(
            ["playback_source_id"], ["playback_sources.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scene_notes_playback_source_id"),
        "scene_notes",
        ["playback_source_id"],
        unique=False,
    )
    op.create_index(op.f("ix_scene_notes_profile_id"), "scene_notes", ["profile_id"], unique=False)
    op.create_index(
        "ix_scene_notes_profile_source",
        "scene_notes",
        ["profile_id", "playback_source_id"],
        unique=False,
    )
    op.create_index(op.f("ix_scene_notes_scene_id"), "scene_notes", ["scene_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scene_notes_scene_id"), table_name="scene_notes")
    op.drop_index("ix_scene_notes_profile_source", table_name="scene_notes")
    op.drop_index(op.f("ix_scene_notes_profile_id"), table_name="scene_notes")
    op.drop_index(op.f("ix_scene_notes_playback_source_id"), table_name="scene_notes")
    op.drop_table("scene_notes")
    op.drop_index(op.f("ix_scene_bookmarks_scene_id"), table_name="scene_bookmarks")
    op.drop_index("ix_scene_bookmarks_profile_source", table_name="scene_bookmarks")
    op.drop_index(op.f("ix_scene_bookmarks_profile_id"), table_name="scene_bookmarks")
    op.drop_index(op.f("ix_scene_bookmarks_playback_source_id"), table_name="scene_bookmarks")
    op.drop_table("scene_bookmarks")
    # ### end Alembic commands ###
