"""scene intelligence foundation

Revision ID: 20260815_0012
Revises: 20260815_0011
Create Date: 2026-08-15 19:47:21.431675
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260815_0012"
down_revision: str | Sequence[str] | None = "20260815_0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scene_intelligence_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("playback_source_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "draft", "review", "validated", "published", name="scene_intelligence_version_state"
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("created_by_admin_id", sa.UUID(), nullable=False),
        sa.Column("validated_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("number > 0", name="ck_scene_versions_number_positive"),
        sa.ForeignKeyConstraint(["created_by_admin_id"], ["admins.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["playback_source_id"], ["playback_sources.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["validated_by_admin_id"], ["admins.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playback_source_id", "number", name="uq_scene_versions_source_number"),
    )
    op.create_index(
        op.f("ix_scene_intelligence_versions_playback_source_id"),
        "scene_intelligence_versions",
        ["playback_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scene_intelligence_versions_state"),
        "scene_intelligence_versions",
        ["state"],
        unique=False,
    )
    op.create_table(
        "scene_intelligence_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("queued", "running", "failed", "completed", name="scene_enrichment_job_state"),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=100), server_default="queued", nullable=False),
        sa.Column("progress_percent", sa.Integer(), server_default="0", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("created_by_admin_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "progress_percent >= 0 AND progress_percent <= 100", name="ck_scene_jobs_progress"
        ),
        sa.ForeignKeyConstraint(["created_by_admin_id"], ["admins.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["version_id"], ["scene_intelligence_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scene_intelligence_jobs_state"), "scene_intelligence_jobs", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_scene_intelligence_jobs_version_id"),
        "scene_intelligence_jobs",
        ["version_id"],
        unique=False,
    )
    op.create_index(
        "ix_scene_jobs_state_created",
        "scene_intelligence_jobs",
        ["state", "created_at"],
        unique=False,
    )
    op.create_table(
        "scene_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "manual",
                "subtitle",
                "transcript",
                "chapter",
                "production",
                "external",
                name="scene_provenance_kind",
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("source_uri", sa.String(length=1000), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("license_basis", sa.String(length=500), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_admin_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_admin_id"], ["admins.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["version_id"], ["scene_intelligence_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scene_sources_version_id"), "scene_sources", ["version_id"], unique=False
    )
    op.create_table(
        "chapters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("start_seconds", sa.Float(), nullable=False),
        sa.Column("end_seconds", sa.Float(), nullable=False),
        sa.CheckConstraint("ordinal > 0", name="ck_chapters_ordinal_positive"),
        sa.CheckConstraint(
            "start_seconds >= 0 AND end_seconds > start_seconds", name="ck_chapters_time_range"
        ),
        sa.ForeignKeyConstraint(["source_id"], ["scene_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["version_id"], ["scene_intelligence_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "ordinal", name="uq_chapters_version_ordinal"),
    )
    op.create_index(op.f("ix_chapters_version_id"), "chapters", ["version_id"], unique=False)
    op.create_table(
        "scenes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("manually_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("start_seconds", sa.Float(), nullable=False),
        sa.Column("end_seconds", sa.Float(), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_scenes_confidence"),
        sa.CheckConstraint("ordinal > 0", name="ck_scenes_ordinal_positive"),
        sa.CheckConstraint(
            "start_seconds >= 0 AND end_seconds > start_seconds", name="ck_scenes_time_range"
        ),
        sa.ForeignKeyConstraint(["source_id"], ["scene_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["version_id"], ["scene_intelligence_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "ordinal", name="uq_scenes_version_ordinal"),
    )
    op.create_index(op.f("ix_scenes_source_id"), "scenes", ["source_id"], unique=False)
    op.create_index(op.f("ix_scenes_version_id"), "scenes", ["version_id"], unique=False)
    op.create_index(
        "ix_scenes_version_time",
        "scenes",
        ["version_id", "start_seconds", "end_seconds"],
        unique=False,
    )
    op.create_table(
        "spoiler_boundaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reveal_seconds", sa.Float(), nullable=False),
        sa.CheckConstraint("reveal_seconds >= 0", name="ck_spoiler_boundaries_reveal"),
        sa.ForeignKeyConstraint(["source_id"], ["scene_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["version_id"], ["scene_intelligence_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spoiler_boundaries_version_id"), "spoiler_boundaries", ["version_id"], unique=False
    )
    op.create_table(
        "music_cues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scene_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("composer", sa.String(length=250), nullable=True),
        sa.Column("performer", sa.String(length=250), nullable=True),
        sa.Column("start_seconds", sa.Float(), nullable=False),
        sa.Column("end_seconds", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "start_seconds >= 0 AND end_seconds > start_seconds", name="ck_music_cues_time_range"
        ),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["scene_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_music_cues_scene_id"), "music_cues", ["scene_id"], unique=False)
    op.create_table(
        "production_notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scene_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("reveal_seconds", sa.Float(), nullable=False),
        sa.CheckConstraint("reveal_seconds >= 0", name="ck_production_notes_reveal"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["scene_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_production_notes_scene_id"), "production_notes", ["scene_id"], unique=False
    )
    op.create_table(
        "scene_characters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scene_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reveal_seconds", sa.Float(), nullable=False),
        sa.Column("manually_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_scene_characters_confidence"
        ),
        sa.CheckConstraint("reveal_seconds >= 0", name="ck_scene_characters_reveal"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["scene_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scene_id", "character_id", name="uq_scene_characters_scene_character"),
    )
    op.create_index(
        op.f("ix_scene_characters_character_id"), "scene_characters", ["character_id"], unique=False
    )
    op.create_index(
        op.f("ix_scene_characters_scene_id"), "scene_characters", ["scene_id"], unique=False
    )
    op.create_table(
        "scene_entities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scene_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("canonical_key", sa.String(length=280), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reveal_seconds", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_scene_entities_confidence"
        ),
        sa.CheckConstraint("reveal_seconds >= 0", name="ck_scene_entities_reveal"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["scene_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scene_id", "canonical_key", name="uq_scene_entities_scene_key"),
    )
    op.create_index(
        op.f("ix_scene_entities_scene_id"), "scene_entities", ["scene_id"], unique=False
    )
    op.create_table(
        "scene_relationships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scene_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("subject_entity_id", sa.UUID(), nullable=False),
        sa.Column("object_entity_id", sa.UUID(), nullable=False),
        sa.Column("relationship", sa.String(length=250), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reveal_seconds", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_scene_relationships_confidence"
        ),
        sa.CheckConstraint("reveal_seconds >= 0", name="ck_scene_relationships_reveal"),
        sa.CheckConstraint(
            "subject_entity_id <> object_entity_id", name="ck_scene_relationships_distinct"
        ),
        sa.ForeignKeyConstraint(["object_entity_id"], ["scene_entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["scene_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_entity_id"], ["scene_entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scene_relationships_scene_id"), "scene_relationships", ["scene_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scene_relationships_scene_id"), table_name="scene_relationships")
    op.drop_table("scene_relationships")
    op.drop_index(op.f("ix_scene_entities_scene_id"), table_name="scene_entities")
    op.drop_table("scene_entities")
    op.drop_index(op.f("ix_scene_characters_scene_id"), table_name="scene_characters")
    op.drop_index(op.f("ix_scene_characters_character_id"), table_name="scene_characters")
    op.drop_table("scene_characters")
    op.drop_index(op.f("ix_production_notes_scene_id"), table_name="production_notes")
    op.drop_table("production_notes")
    op.drop_index(op.f("ix_music_cues_scene_id"), table_name="music_cues")
    op.drop_table("music_cues")
    op.drop_index(op.f("ix_spoiler_boundaries_version_id"), table_name="spoiler_boundaries")
    op.drop_table("spoiler_boundaries")
    op.drop_index("ix_scenes_version_time", table_name="scenes")
    op.drop_index(op.f("ix_scenes_version_id"), table_name="scenes")
    op.drop_index(op.f("ix_scenes_source_id"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_chapters_version_id"), table_name="chapters")
    op.drop_table("chapters")
    op.drop_index(op.f("ix_scene_sources_version_id"), table_name="scene_sources")
    op.drop_table("scene_sources")
    op.drop_index("ix_scene_jobs_state_created", table_name="scene_intelligence_jobs")
    op.drop_index(
        op.f("ix_scene_intelligence_jobs_version_id"), table_name="scene_intelligence_jobs"
    )
    op.drop_index(op.f("ix_scene_intelligence_jobs_state"), table_name="scene_intelligence_jobs")
    op.drop_table("scene_intelligence_jobs")
    op.drop_index(
        op.f("ix_scene_intelligence_versions_state"), table_name="scene_intelligence_versions"
    )
    op.drop_index(
        op.f("ix_scene_intelligence_versions_playback_source_id"),
        table_name="scene_intelligence_versions",
    )
    op.drop_table("scene_intelligence_versions")
    op.execute("DROP TYPE IF EXISTS scene_provenance_kind")
    op.execute("DROP TYPE IF EXISTS scene_enrichment_job_state")
    op.execute("DROP TYPE IF EXISTS scene_intelligence_version_state")
    # ### end Alembic commands ###
