"""scene ingestion and search index

Revision ID: 20260815_0013
Revises: 20260815_0012
Create Date: 2026-08-15 20:00:30.564647
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260815_0013"
down_revision: str | Sequence[str] | None = "20260815_0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scene_search_documents",
        sa.Column("scene_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("searchable_text", sa.Text(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', coalesce(searchable_text, ''))", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["version_id"], ["scene_intelligence_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("scene_id"),
    )
    op.create_index(
        "ix_scene_search_documents_vector",
        "scene_search_documents",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_scene_search_documents_version_id"),
        "scene_search_documents",
        ["version_id"],
        unique=False,
    )
    op.create_table(
        "transcript_cues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("scene_id", sa.UUID(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("speaker_label", sa.String(length=250), nullable=True),
        sa.Column("confidence", sa.Float(), server_default="1", nullable=False),
        sa.Column("start_seconds", sa.Float(), nullable=False),
        sa.Column("end_seconds", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "start_seconds >= 0 AND end_seconds > start_seconds",
            name="ck_transcript_cues_time_range",
        ),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["scene_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["version_id"], ["scene_intelligence_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcript_cues_scene_id"), "transcript_cues", ["scene_id"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_cues_source_id"), "transcript_cues", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_cues_version_id"), "transcript_cues", ["version_id"], unique=False
    )
    op.create_index(
        "ix_transcript_cues_version_time",
        "transcript_cues",
        ["version_id", "start_seconds", "end_seconds"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transcript_cues_version_time", table_name="transcript_cues")
    op.drop_index(op.f("ix_transcript_cues_version_id"), table_name="transcript_cues")
    op.drop_index(op.f("ix_transcript_cues_source_id"), table_name="transcript_cues")
    op.drop_index(op.f("ix_transcript_cues_scene_id"), table_name="transcript_cues")
    op.drop_table("transcript_cues")
    op.drop_index(op.f("ix_scene_search_documents_version_id"), table_name="scene_search_documents")
    op.drop_index(
        "ix_scene_search_documents_vector",
        table_name="scene_search_documents",
        postgresql_using="gin",
    )
    op.drop_table("scene_search_documents")
    # ### end Alembic commands ###
