"""ask movie provenance logs

Revision ID: 20260815_0015
Revises: 20260815_0014
Create Date: 2026-08-15 20:32:58.659948
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260815_0015"
down_revision: str | Sequence[str] | None = "20260815_0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ask_movie_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("playback_source_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=True),
        sa.Column("timestamp_seconds", sa.Float(), nullable=False),
        sa.Column("spoiler_mode", sa.String(length=20), nullable=False),
        sa.Column("question_sha256", sa.String(length=64), nullable=False),
        sa.Column("intent", sa.String(length=50), nullable=False),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("provenance", sa.JSON(), server_default="[]", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("timestamp_seconds >= 0", name="ck_ask_movie_logs_timestamp"),
        sa.ForeignKeyConstraint(
            ["playback_source_id"], ["playback_sources.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["version_id"], ["scene_intelligence_versions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ask_movie_logs_playback_source_id"),
        "ask_movie_logs",
        ["playback_source_id"],
        unique=False,
    )
    op.create_index(
        "ix_ask_movie_logs_profile_created",
        "ask_movie_logs",
        ["profile_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ask_movie_logs_profile_id"), "ask_movie_logs", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_ask_movie_logs_version_id"), "ask_movie_logs", ["version_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ask_movie_logs_version_id"), table_name="ask_movie_logs")
    op.drop_index(op.f("ix_ask_movie_logs_profile_id"), table_name="ask_movie_logs")
    op.drop_index("ix_ask_movie_logs_profile_created", table_name="ask_movie_logs")
    op.drop_index(op.f("ix_ask_movie_logs_playback_source_id"), table_name="ask_movie_logs")
    op.drop_table("ask_movie_logs")
    # ### end Alembic commands ###
