"""Atomic ownership fence for the Redis database reserved for browser tests."""

from __future__ import annotations

import ctypes
import errno
import hashlib
import ipaddress
import json
import os
import re
import socket
from ctypes import wintypes
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from typing import Any
from urllib.parse import urlsplit

import redis

E2E_REDIS_DATABASE = 14
OWNER_KEY = "aperture:e2e:redis-owner:v1"
OWNER_VERSION = 1
RUN_ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]{6,38}[a-z0-9]$")
TOKEN_PATTERN = re.compile(r"^[a-f0-9]{64}$")

ACQUIRE_OWNER = """
local current = redis.call('GET', KEYS[1])
if current then return {'existing', current} end
local size = redis.call('DBSIZE')
if size ~= 0 then return {'dirty', tostring(size)} end
redis.call('SET', KEYS[1], ARGV[1])
return {'acquired', ARGV[1]}
"""

RECLAIM_OWNER = """
local current = redis.call('GET', KEYS[1])
if current ~= ARGV[1] then return 0 end
redis.call('FLUSHDB')
redis.call('SET', KEYS[1], ARGV[2])
return 1
"""

RELEASE_OWNER = """
local current = redis.call('GET', KEYS[1])
if current ~= ARGV[1] then return 0 end
redis.call('FLUSHDB')
return 1
"""


class E2ERedisFenceError(RuntimeError):
    """Raised when DB14 cannot be proven safe for the requesting E2E run."""


@dataclass(frozen=True)
class RedisOwner:
    version: int
    run_id: str
    token_sha256: str
    hostname: str
    pid: int
    acquired_at: str

    def encoded(self) -> str:
        return json.dumps(asdict(self), separators=(",", ":"), sort_keys=True)


def token_sha256(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def _validate_identity(run_id: str, token: str) -> None:
    if not RUN_ID_PATTERN.fullmatch(run_id):
        raise E2ERedisFenceError("E2E_RUN_ID is not a valid isolated run identifier")
    if not TOKEN_PATTERN.fullmatch(token):
        raise E2ERedisFenceError(
            "E2E_OWNER_TOKEN must be the 64-character secret generated by the E2E wrapper"
        )


def _redis_database(redis_url: str) -> int:
    parsed = urlsplit(redis_url)
    if parsed.scheme not in {"redis", "rediss"}:
        raise E2ERedisFenceError("REDIS_URL must use the redis or rediss protocol")
    if parsed.query or parsed.fragment:
        raise E2ERedisFenceError(
            "REDIS_URL must not contain a query or fragment that can override database 14"
        )
    hostname = (parsed.hostname or "").rstrip(".").lower()
    if hostname != "localhost":
        try:
            address = ipaddress.ip_address(hostname)
        except ValueError:
            raise E2ERedisFenceError("E2E Redis must use a loopback host") from None
        if not address.is_loopback:
            raise E2ERedisFenceError("E2E Redis must use a loopback host")
    path = parsed.path.removeprefix("/")
    if not path.isdigit():
        raise E2ERedisFenceError("REDIS_URL must select an explicit logical database")
    return int(path)


def _require_reserved_database(redis_url: str) -> None:
    if _redis_database(redis_url) != E2E_REDIS_DATABASE:
        raise E2ERedisFenceError(
            f"E2E Redis ownership is restricted to database {E2E_REDIS_DATABASE}"
        )


def _decode(value: Any) -> str:
    if isinstance(value, bytes):
        return value.decode("utf-8")
    return str(value)


def _parse_owner(raw: str) -> RedisOwner:
    try:
        value = json.loads(raw)
        owner = RedisOwner(
            version=value["version"],
            run_id=value["run_id"],
            token_sha256=value["token_sha256"],
            hostname=value["hostname"],
            pid=value["pid"],
            acquired_at=value["acquired_at"],
        )
    except (KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
        raise E2ERedisFenceError(
            "Redis DB14 has a malformed owner record; refusing to modify it"
        ) from exc
    if (
        owner.version != OWNER_VERSION
        or not RUN_ID_PATTERN.fullmatch(owner.run_id)
        or not TOKEN_PATTERN.fullmatch(owner.token_sha256)
        or not isinstance(owner.hostname, str)
        or not owner.hostname.strip()
        or not isinstance(owner.pid, int)
        or owner.pid <= 0
        or not isinstance(owner.acquired_at, str)
        or not owner.acquired_at
    ):
        raise E2ERedisFenceError(
            "Redis DB14 has an invalid owner record; refusing to modify it"
        )
    return owner


def _new_owner(run_id: str, token: str, pid: int) -> RedisOwner:
    if pid <= 0:
        raise E2ERedisFenceError("E2E owner PID must be positive")
    return RedisOwner(
        version=OWNER_VERSION,
        run_id=run_id,
        token_sha256=token_sha256(token),
        hostname=socket.gethostname(),
        pid=pid,
        acquired_at=datetime.now(UTC).isoformat(),
    )


def _windows_process_is_alive(pid: int) -> bool:
    process_query_limited_information = 0x1000
    still_active = 259
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    kernel32.OpenProcess.argtypes = (wintypes.DWORD, wintypes.BOOL, wintypes.DWORD)
    kernel32.OpenProcess.restype = wintypes.HANDLE
    kernel32.GetExitCodeProcess.argtypes = (wintypes.HANDLE, ctypes.POINTER(wintypes.DWORD))
    kernel32.GetExitCodeProcess.restype = wintypes.BOOL
    kernel32.CloseHandle.argtypes = (wintypes.HANDLE,)
    kernel32.CloseHandle.restype = wintypes.BOOL
    handle = kernel32.OpenProcess(process_query_limited_information, False, pid)
    if not handle:
        error = ctypes.get_last_error()
        if error in {5}:  # Access denied means a process exists, but is not inspectable.
            return True
        return False
    try:
        exit_code = wintypes.DWORD()
        if not kernel32.GetExitCodeProcess(handle, ctypes.byref(exit_code)):
            return True
        return exit_code.value == still_active
    finally:
        kernel32.CloseHandle(handle)


def process_is_alive(pid: int) -> bool:
    """Conservatively report whether a recorded local owner process still exists."""

    if os.name == "nt":
        return _windows_process_is_alive(pid)
    try:
        os.kill(pid, 0)
    except OSError as exc:
        if exc.errno == errno.ESRCH:
            return False
        return True
    return True


def _client(redis_url: str) -> redis.Redis:
    return redis.Redis.from_url(
        redis_url,
        socket_connect_timeout=3,
        socket_timeout=3,
        decode_responses=False,
    )


def acquire_owner(
    redis_url: str,
    run_id: str,
    token: str,
    pid: int,
    *,
    reclaim_dead_local: bool = False,
    client: Any | None = None,
) -> RedisOwner:
    """Atomically claim an empty DB14, optionally replacing a proven-dead local owner."""

    _require_reserved_database(redis_url)
    _validate_identity(run_id, token)
    desired = _new_owner(run_id, token, pid)
    owns_client = client is None
    redis_client = client or _client(redis_url)
    try:
        result = redis_client.eval(ACQUIRE_OWNER, 1, OWNER_KEY, desired.encoded())
        state, payload = (_decode(result[0]), _decode(result[1]))
        if state == "acquired":
            return desired
        if state == "dirty":
            raise E2ERedisFenceError(
                "Redis DB14 contains unknown preexisting keys and has no owner; "
                "refusing to inspect, flush, or claim it"
            )
        if state != "existing":
            raise E2ERedisFenceError("Redis DB14 returned an invalid ownership response")

        existing = _parse_owner(payload)
        if (
            existing.run_id == desired.run_id
            and existing.token_sha256 == desired.token_sha256
            and existing.hostname.casefold() == desired.hostname.casefold()
            and existing.pid == desired.pid
        ):
            return existing
        if not reclaim_dead_local:
            raise E2ERedisFenceError(
                f"Redis DB14 is owned by E2E run {existing.run_id!r} "
                f"on {existing.hostname} (PID {existing.pid}); refusing concurrent access"
            )
        if existing.hostname.casefold() != socket.gethostname().casefold():
            raise E2ERedisFenceError(
                "Redis DB14 owner is not local; its liveness cannot be proven safely"
            )
        if process_is_alive(existing.pid):
            raise E2ERedisFenceError(
                f"Redis DB14 owner PID {existing.pid} is still active; refusing reclaim"
            )
        reclaimed = redis_client.eval(
            RECLAIM_OWNER,
            1,
            OWNER_KEY,
            payload,
            desired.encoded(),
        )
        if int(reclaimed) != 1:
            raise E2ERedisFenceError(
                "Redis DB14 ownership changed during reclaim; refusing to continue"
            )
        return desired
    except redis.RedisError as exc:
        raise E2ERedisFenceError(f"Redis DB14 ownership check failed: {exc}") from exc
    finally:
        if owns_client:
            redis_client.close()


def verify_owner(
    redis_url: str,
    run_id: str,
    token: str,
    *,
    client: Any | None = None,
) -> RedisOwner:
    """Return the current owner only when it matches this run and secret."""

    _require_reserved_database(redis_url)
    _validate_identity(run_id, token)
    owns_client = client is None
    redis_client = client or _client(redis_url)
    try:
        raw_value = redis_client.get(OWNER_KEY)
        if raw_value is None:
            raise E2ERedisFenceError("Redis DB14 has no E2E owner")
        owner = _parse_owner(_decode(raw_value))
        if owner.run_id != run_id or owner.token_sha256 != token_sha256(token):
            raise E2ERedisFenceError("Redis DB14 is owned by a different E2E run")
        return owner
    except redis.RedisError as exc:
        raise E2ERedisFenceError(f"Redis DB14 ownership check failed: {exc}") from exc
    finally:
        if owns_client:
            redis_client.close()


def release_owner(
    redis_url: str,
    run_id: str,
    token: str,
    *,
    client: Any | None = None,
) -> None:
    """Atomically flush DB14 only when the exact requesting owner still holds it."""

    owns_client = client is None
    redis_client = client or _client(redis_url)
    try:
        owner = verify_owner(redis_url, run_id, token, client=redis_client)
        released = redis_client.eval(RELEASE_OWNER, 1, OWNER_KEY, owner.encoded())
        if int(released) != 1:
            raise E2ERedisFenceError(
                "Redis DB14 ownership changed during release; refusing to flush it"
            )
    except redis.RedisError as exc:
        raise E2ERedisFenceError(f"Redis DB14 release failed: {exc}") from exc
    finally:
        if owns_client:
            redis_client.close()
