import Link from "next/link";
import { SiteHeader } from "@/app/components/site-header";
import { customerAccountFetch, type AccountDashboard } from "@/app/lib/account";
import { requireCustomerSession } from "@/app/lib/customer-session";
import { PasswordForm } from "./password-form";
import { openBillingPortal, revokeOtherSessions, revokeSession, setLanguagePreferences, setPrivacyPreferences, setRewatchIntelligence, startCheckout } from "./actions";

const languages = [["en", "English"], ["fr", "Français"], ["es", "Español"], ["ar", "العربية"], ["ja", "日本語"]];
const timezones = ["UTC", "America/Toronto", "America/New_York", "America/Los_Angeles", "Europe/London", "Europe/Paris", "Asia/Tokyo"];

function deviceName(agent: string | null) {
  if (!agent) return "Unknown device";
  if (/mobile|android|iphone/i.test(agent)) return "Mobile browser";
  if (/tv/i.test(agent)) return "TV device";
  return "Desktop browser";
}
export default async function AccountPage() {
  const [viewer, dashboard] = await Promise.all([
    requireCustomerSession(), customerAccountFetch<AccountDashboard>("/account"),
  ]);
  const activeProfile = viewer.profiles.find((profile) => profile.id === viewer.active_profile_id) ?? viewer.profiles[0];
  const locale = activeProfile?.language ?? "en";
  const timezone = activeProfile?.preference.timezone ?? "UTC";
  return <main className="account-page"><SiteHeader />
    <header className="account-heading"><p className="eyebrow">Viewer account</p><h1>Account & access</h1><p>{dashboard.email} · {viewer.profiles.length} profile{viewer.profiles.length === 1 ? "" : "s"}</p></header>
    <div className="account-grid">
      <section className="account-panel account-subscription"><p className="eyebrow">Subscription</p><h2>{dashboard.subscription ? dashboard.subscription.plan.name : "No active subscription"}</h2>
        {dashboard.subscription ? <><span className={`catalog-badge ${dashboard.subscription.status}`}>{dashboard.subscription.status}</span><p>{dashboard.subscription.plan.description}</p><dl><div><dt>Quality</dt><dd>{dashboard.subscription.plan.max_resolution}</dd></div><div><dt>Streams</dt><dd>{dashboard.subscription.plan.max_streams}</dd></div><div><dt>Provider</dt><dd>{dashboard.subscription.provider}</dd></div></dl>{dashboard.billing.production_ready && <form action={openBillingPortal}><button type="submit" className="secondary">Manage billing</button></form>}</> : <p>{dashboard.billing.checkout_available ? "Choose a plan to continue securely with the billing provider." : "Choose a plan once a production billing provider is connected. No payment has been recorded."}</p>}
        {dashboard.billing.notice && <div className="billing-notice"><strong>Billing unavailable</strong><p>{dashboard.billing.notice}</p></div>}
      </section>
      <section className="account-panel"><div className="rail-heading"><div><p className="eyebrow">Profiles</p><h2>Who&apos;s watching</h2></div><Link href="/profiles">Manage</Link></div><ul className="account-profile-list">{viewer.profiles.map((profile) => <li key={profile.id}><span className="mini-avatar">{profile.name[0]}</span><div><strong>{profile.name}</strong><small>{profile.is_kids ? "Kids profile" : `${profile.maturity_level} · ${profile.language}`}</small><small>Rewatch intelligence {profile.preference.rewatch_intelligence_enabled ? "on" : "off"}</small></div><form action={setRewatchIntelligence.bind(null, profile.id, profile.preference, !profile.preference.rewatch_intelligence_enabled)}><button type="submit">Turn {profile.preference.rewatch_intelligence_enabled ? "off" : "on"}</button></form></li>)}</ul></section>
      <section className="account-panel account-wide"><p className="eyebrow">Language & accessibility</p><h2>Audio, captions, and local time</h2><p>Preferences are private to each profile and applied when playback starts.</p><div className="language-preference-grid">{viewer.profiles.map((profile) => <form key={profile.id} className="language-preference" action={setLanguagePreferences.bind(null, profile.id, profile.preference)}><h3>{profile.name}</h3><label>Interface language<select name="language" defaultValue={profile.language}>{languages.map(([code, name]) => <option value={code} key={code}>{name}</option>)}</select></label><label>Preferred audio<select name="preferred_audio_language" defaultValue={profile.preference.preferred_audio_language ?? profile.language}>{languages.map(([code, name]) => <option value={code} key={code}>{name}</option>)}</select></label><label>Preferred subtitles<select name="preferred_subtitle_language" defaultValue={profile.preference.preferred_subtitle_language ?? profile.language}>{languages.map(([code, name]) => <option value={code} key={code}>{name}</option>)}</select></label><label>Second subtitle<select name="preferred_secondary_subtitle_language" defaultValue={profile.preference.preferred_secondary_subtitle_language ?? ""}><option value="">Off</option>{languages.map(([code, name]) => <option value={code} key={code}>{name}</option>)}</select></label><label>Caption size<select name="caption_size" defaultValue={profile.preference.caption_size}><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select></label><label>Caption background<select name="caption_background" defaultValue={profile.preference.caption_background}><option value="transparent">Transparent</option><option value="shadow">Text shadow</option><option value="solid">Solid</option></select></label><label>Caption position<select name="caption_position" defaultValue={profile.preference.caption_position}><option value="bottom">Bottom</option><option value="top">Top</option></select></label><label>Timezone<select name="timezone" defaultValue={profile.preference.timezone}>{timezones.map((zone) => <option value={zone} key={zone}>{zone.replaceAll("_", " ")}</option>)}</select></label><label className="check-line"><input type="checkbox" name="subtitles_enabled" defaultChecked={profile.preference.subtitles_enabled} /> Enable subtitles by default</label><button className="secondary">Save language preferences</button></form>)}</div></section>
      <section className="account-panel account-wide"><p className="eyebrow">Privacy & consent</p><h2>Optional analytics and personalization</h2><p>Playback progress is required to resume viewing and is separate from optional product analytics. Turning analytics off stops new event collection and deletes this profile&apos;s retained raw analytics; anonymous aggregates already produced cannot identify the profile.</p><div className="language-preference-grid">{viewer.profiles.map((profile) => <form key={profile.id} className="language-preference" action={setPrivacyPreferences.bind(null, profile.id)}><h3>{profile.name}</h3><label className="check-line"><input type="checkbox" name="analytics_enabled" defaultChecked={profile.preference.analytics_enabled} /> Share optional usage and playback-quality analytics</label><label>Homepage personalization<select name="homepage_mode" defaultValue={profile.preference.homepage_mode}><option value="no_algorithm">No Algorithm</option><option value="curated">Curated profile experience</option></select></label>{profile.preference.consent_updated_at ? <small>Last changed <time dateTime={profile.preference.consent_updated_at}>{new Intl.DateTimeFormat(locale, { dateStyle:"medium", timeStyle:"short", timeZone:timezone }).format(new Date(profile.preference.consent_updated_at))}</time></small> : <small>No analytics consent has been recorded.</small>}<button className="secondary">Save privacy choices</button></form>)}</div></section>
      <section className="account-panel account-wide"><div className="rail-heading"><div><p className="eyebrow">Security</p><h2>Devices & sessions</h2></div>{dashboard.sessions.length > 1 && <form action={revokeOtherSessions}><button className="secondary">Sign out other sessions</button></form>}</div>
        <ul className="session-list">{dashboard.sessions.map((session) => <li key={session.id}><div><strong>{deviceName(session.user_agent)} {session.current && <span className="catalog-badge active">Current</span>}</strong><small>{session.user_agent ?? "User agent unavailable"}</small><small>Last active <time dateTime={session.last_seen_at}>{new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(session.last_seen_at))}</time> · IP {session.ip_address ?? "unavailable"}</small></div>{!session.current && <form action={revokeSession.bind(null, session.id)}><button>Sign out</button></form>}</li>)}</ul>
      </section>
      <section className="account-panel"><p className="eyebrow">Security</p><h2>Change password</h2><PasswordForm /></section>
      <section className="account-panel"><p className="eyebrow">Available plans</p><h2>Provider-ready catalog</h2><div className="plan-list">{dashboard.plans.map((plan) => <article key={plan.id}><strong>{plan.name}</strong><span>{new Intl.NumberFormat(locale, { style: "currency", currency: plan.currency }).format(plan.price_cents / 100)} / {plan.interval}</span><p>{plan.description}</p>{dashboard.billing.checkout_available && !dashboard.subscription ? <form action={startCheckout.bind(null, plan.code)}><button type="submit">Choose {plan.name}</button></form> : <button disabled title={dashboard.subscription ? "Manage your existing subscription above" : "A production billing provider is not configured"}>{dashboard.subscription ? "Current account subscribed" : "Checkout unavailable"}</button>}</article>)}</div></section>
    </div>
  </main>;
}
